algo = input('Digite algo: ')
print(f'O tipo primitivo de {algo} é', type(algo))
print(f'Só tem espaços? {algo.isspace()}')
print(f'É um numero? {algo.isnumeric()}')
print(f'É alfabeto? {algo.isalpha()}')
print(f'É alfanumérico? {algo.isalnum()}')
print(f'Esta em maiuscula? {algo.isupper()}')
print(f'Esta em minuscula? {algo.islower()}')
print(f'Está capitalizada? {algo.istitle()}')
print(f'Esta capitalizada? {algo.istitle()}')
